#서버 설정
server:
  port: 8092
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
#뷰리졸버 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/fighting/
      suffix: .jsp

#데이터소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: 

#jpa 설정
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      user-new-id-generator-mappings: false;
    properties:
      hibernate.format_sql: true  
     
